2013-11-25T11:24:12.139803+00:00 app[web.1]: 2013-11-25 11:24:12 [2] [INFO] Handling signal: term
2013-11-25T11:24:12.165282+00:00 app[web.1]: 2013-11-25 11:24:12 [2] [INFO] Shutting down: Master
2013-11-25T11:24:13.553208+00:00 heroku[web.1]: Starting process with command `gunicorn rosterrun:app`
2013-11-25T11:24:13.584027+00:00 heroku[web.1]: Process exited with status 0
2013-11-25T11:24:14.957018+00:00 app[web.1]: 2013-11-25 11:24:14 [2] [INFO] Listening at: http://0.0.0.0:34010 (2)
2013-11-25T11:24:14.956410+00:00 app[web.1]: 2013-11-25 11:24:14 [2] [INFO] Starting gunicorn 18.0
2013-11-25T11:24:14.957076+00:00 app[web.1]: 2013-11-25 11:24:14 [2] [INFO] Using worker: sync
2013-11-25T11:24:14.969010+00:00 app[web.1]: 2013-11-25 11:24:14 [7] [INFO] Booting worker with pid: 7
2013-11-25T11:24:15.306231+00:00 heroku[web.1]: State changed from starting to up
2013-11-25T11:24:26.180941+00:00 heroku[api]: Starting process with command `python` by andygee@gmail.com
2013-11-25T11:24:31.535143+00:00 heroku[run.5341]: State changed from starting to up
2013-11-25T11:24:31.610862+00:00 heroku[run.5341]: Awaiting client
2013-11-25T11:24:31.644961+00:00 heroku[run.5341]: Starting process with command `python`
2013-11-25T11:24:48.556899+00:00 heroku[run.5341]: State changed from up to complete
2013-11-25T11:24:48.545241+00:00 heroku[run.5341]: Process exited with status 0
2013-11-25T11:25:08.914426+00:00 heroku[router]: at=info method=GET path=/ host=rosterrun.herokuapp.com fwd="67.188.246.249" dyno=web.1 connect=1ms service=292ms status=200 bytes=684
2013-11-25T11:25:14.464604+00:00 heroku[router]: at=info method=GET path=/ host=rosterrun.herokuapp.com fwd="67.188.246.249" dyno=web.1 connect=1ms service=115ms status=200 bytes=818
2013-11-25T11:25:19.711536+00:00 heroku[router]: at=info method=GET path=/logout host=rosterrun.herokuapp.com fwd="67.188.246.249" dyno=web.1 connect=1ms service=9ms status=302 bytes=209
2013-11-25T11:25:20.200896+00:00 heroku[router]: at=info method=GET path=/ host=rosterrun.herokuapp.com fwd="67.188.246.249" dyno=web.1 connect=1ms service=117ms status=200 bytes=509
2013-11-25T11:25:22.418531+00:00 heroku[router]: at=info method=GET path=/login host=rosterrun.herokuapp.com fwd="67.188.246.249" dyno=web.1 connect=1ms service=12ms status=200 bytes=492
2013-11-25T11:25:30.564074+00:00 heroku[router]: at=info method=POST path=/login host=rosterrun.herokuapp.com fwd="67.188.246.249" dyno=web.1 connect=1ms service=5ms status=302 bytes=209
2013-11-25T11:25:31.380844+00:00 heroku[router]: at=info method=GET path=/ host=rosterrun.herokuapp.com fwd="67.188.246.249" dyno=web.1 connect=1ms service=5ms status=200 bytes=733
2013-11-25T11:25:39.609253+00:00 app[web.1]: dual client assignment [('Andy', 'SPKiller'), ('Andy', 'Healer'), ('Joe', 'SPActive'), ('Joe', 'Freezer'), ('Cheng', 'Support'), ('Cheng', 'Lurer')]
2013-11-25T11:25:39.941815+00:00 app[web.1]: dual client assignment [('Andy', 'SPKiller'), ('Andy', 'Lurer'), ('Joe', 'SPActive'), ('Joe', 'Freezer'), ('Cheng', 'Support'), ('Cheng', 'Healer')]
2013-11-25T11:25:40.173170+00:00 app[web.1]: dual client assignment [('Andy', 'SPKiller'), ('Andy', 'Support'), ('Joe', 'SPActive'), ('Joe', 'Freezer'), ('Cheng', 'Healer'), ('Cheng', 'Lurer')]
2013-11-25T11:25:42.914298+00:00 app[web.1]: dual client assignment [('Andy', 'Healer'), ('Andy', 'Support')]
2013-11-25T11:25:42.926429+00:00 app[web.1]: dual client assignment [('Andy', 'Healer'), ('Andy', 'Support'), ('Joe', 'Freezer'), ('Joe', 'Healer')]
2013-11-25T11:25:42.927654+00:00 app[web.1]: dual client assignment [('Andy', 'Healer'), ('Andy', 'Support'), ('Cheng', 'Healer'), ('Cheng', 'Killer')]
2013-11-25T11:25:42.972740+00:00 app[web.1]: dual client assignment [('Joe', 'Support'), ('Joe', 'Freezer')]
2013-11-25T11:25:42.975429+00:00 app[web.1]: dual client assignment [('Cheng', 'Support'), ('Cheng', 'Killer')]
2013-11-25T11:25:43.000919+00:00 app[web.1]: dual client assignment [('Joe', 'Support'), ('Joe', 'Freezer'), ('Cheng', 'Healer'), ('Cheng', 'Killer')]
2013-11-25T11:25:43.004658+00:00 app[web.1]: dual client assignment [('Joe', 'Freezer'), ('Joe', 'Healer'), ('Cheng', 'Support'), ('Cheng', 'Killer')]
2013-11-25T11:25:43.124203+00:00 app[web.1]: dual client assignment [('Joe', 'Freezer'), ('Joe', 'Healer')]
2013-11-25T11:25:43.125542+00:00 app[web.1]: dual client assignment [('Cheng', 'Healer'), ('Cheng', 'Killer')]
2013-11-25T11:25:43.153718+00:00 app[web.1]: dual client assignment [('Joe', 'Freezer'), ('Joe', 'Healer'), ('Cheng', 'Healer'), ('Cheng', 'Killer')]
2013-11-25T11:25:43.219997+00:00 app[web.1]: dual client assignment [('Joe', 'Support'), ('Joe', 'Freezer'), ('Cheng', 'Healer'), ('Cheng', 'Killer')]
2013-11-25T11:25:43.223061+00:00 app[web.1]: dual client assignment [('Joe', 'Freezer'), ('Joe', 'Healer'), ('Cheng', 'Support'), ('Cheng', 'Killer')]
2013-11-25T11:25:43.293176+00:00 app[web.1]: 2013-11-25 11:25:43 [7] [ERROR] Error handling request
2013-11-25T11:25:43.293176+00:00 app[web.1]: Traceback (most recent call last):
2013-11-25T11:25:43.293176+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/workers/sync.py", line 131, in handle_request
2013-11-25T11:25:43.293176+00:00 app[web.1]:     respiter = self.wsgi(environ, resp.start_response)
2013-11-25T11:25:43.293176+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/flask/app.py", line 1836, in __call__
2013-11-25T11:25:43.293176+00:00 app[web.1]:     return self.wsgi_app(environ, start_response)
2013-11-25T11:25:43.293176+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/flask/app.py", line 1820, in wsgi_app
2013-11-25T11:25:43.293176+00:00 app[web.1]:     response = self.make_response(self.handle_exception(e))
2013-11-25T11:25:43.293176+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/flask/app.py", line 1403, in handle_exception
2013-11-25T11:25:43.293176+00:00 app[web.1]:     reraise(exc_type, exc_value, tb)
2013-11-25T11:25:43.293392+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
2013-11-25T11:25:43.293392+00:00 app[web.1]:     response = self.full_dispatch_request()
2013-11-25T11:25:43.293392+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
2013-11-25T11:25:43.293392+00:00 app[web.1]:     rv = self.handle_user_exception(e)
2013-11-25T11:25:43.293392+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
2013-11-25T11:25:43.293392+00:00 app[web.1]:     rv = self.dispatch_request()
2013-11-25T11:25:43.293392+00:00 app[web.1]:     reraise(exc_type, exc_value, tb)
2013-11-25T11:25:43.293392+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
2013-11-25T11:25:43.293392+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
2013-11-25T11:25:43.293536+00:00 app[web.1]:   File "/app/rosterrun.py", line 124, in run_calculation
2013-11-25T11:25:43.293392+00:00 app[web.1]:     return self.view_functions[rule.endpoint](**req.view_args)
2013-11-25T11:25:43.293536+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/sqlalchemy/orm/scoping.py", line 149, in do
2013-11-25T11:25:43.293536+00:00 app[web.1]:     return getattr(self.registry(), name)(*args, **kwargs)
2013-11-25T11:25:43.293536+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 354, in commit
2013-11-25T11:25:43.293536+00:00 app[web.1]:     self._prepare_impl()
2013-11-25T11:25:43.293536+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 334, in _prepare_impl
2013-11-25T11:25:43.293536+00:00 app[web.1]:     self.transaction.commit()
2013-11-25T11:25:43.293536+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 721, in commit
2013-11-25T11:25:43.294020+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 1818, in flush
2013-11-25T11:25:43.294020+00:00 app[web.1]:     self._flush(objects)
2013-11-25T11:25:43.294020+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 1936, in _flush
2013-11-25T11:25:43.293536+00:00 app[web.1]:     db.session.commit()
2013-11-25T11:25:43.294020+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/sqlalchemy/util/langhelpers.py", line 58, in __exit__
2013-11-25T11:25:43.293536+00:00 app[web.1]:     self.session.flush()
2013-11-25T11:25:43.294020+00:00 app[web.1]:     compat.reraise(exc_type, exc_value, exc_tb)
2013-11-25T11:25:43.294020+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 1900, in _flush
2013-11-25T11:25:43.294020+00:00 app[web.1]:     flush_context.execute()
2013-11-25T11:25:43.294169+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/sqlalchemy/orm/persistence.py", line 64, in save_obj
2013-11-25T11:25:43.294169+00:00 app[web.1]:     table, insert)
2013-11-25T11:25:43.294020+00:00 app[web.1]:     rec.execute(self)
2013-11-25T11:25:43.294169+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/sqlalchemy/orm/unitofwork.py", line 525, in execute
2013-11-25T11:25:43.294169+00:00 app[web.1]:     uow
2013-11-25T11:25:43.294020+00:00 app[web.1]:     transaction.rollback(_capture_exception=True)
2013-11-25T11:25:43.294169+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/sqlalchemy/orm/persistence.py", line 569, in _emit_insert_statements
2013-11-25T11:25:43.294169+00:00 app[web.1]:     execute(statement, params)
2013-11-25T11:25:43.294169+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 662, in execute
2013-11-25T11:25:43.294169+00:00 app[web.1]:     params)
2013-11-25T11:25:43.294169+00:00 app[web.1]:     compiled_sql, distilled_params
2013-11-25T11:25:43.294526+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 874, in _execute_context
2013-11-25T11:25:43.294526+00:00 app[web.1]:     context)
2013-11-25T11:25:43.294526+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1024, in _handle_dbapi_exception
2013-11-25T11:25:43.294526+00:00 app[web.1]:     exc_info
2013-11-25T11:25:43.294020+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/sqlalchemy/orm/unitofwork.py", line 372, in execute
2013-11-25T11:25:43.294526+00:00 app[web.1]:     reraise(type(exception), exception, tb=exc_tb)
2013-11-25T11:25:43.294526+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 867, in _execute_context
2013-11-25T11:25:43.294526+00:00 app[web.1]:     context)
2013-11-25T11:25:43.294526+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/sqlalchemy/engine/default.py", line 324, in do_execute
2013-11-25T11:25:43.294526+00:00 app[web.1]:     cursor.execute(statement, parameters)
2013-11-25T11:25:43.294695+00:00 app[web.1]: IntegrityError: (IntegrityError) duplicate key value violates unique constraint "party_combination_g_spreadsheet_id_key"
2013-11-25T11:25:43.294695+00:00 app[web.1]:  'INSERT INTO party_combination (g_spreadsheet_id, g_worksheet_id, "partyIndex", "instanceName", "playerName", name, "className", rolename) VALUES (%(g_spreadsheet_id)s, %(g_worksheet_id)s, %(partyIndex)s, %(instanceName)s, %(playerName)s, %(name)s, %(className)s, %(rolename)s) RETURNING party_combination.id' {'instanceName': 'Niddhogg', 'playerName': 'Andy', 'partyIndex': '0', 'name': 'ctrlx', 'className': 'Clown', 'g_worksheet_id': 'od6', 'rolename': 'Support', 'g_spreadsheet_id': 't0r5xf97B-k70k6TxherGcw'}
2013-11-25T11:25:43.294695+00:00 app[web.1]: DETAIL:  Key (g_spreadsheet_id)=(t0r5xf97B-k70k6TxherGcw) already exists.
2013-11-25T11:25:43.294169+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 761, in _execute_clauseelement
2013-11-25T11:25:43.294526+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/sqlalchemy/util/compat.py", line 196, in raise_from_cause
2013-11-25T11:25:43.292949+00:00 heroku[router]: at=info method=POST path=/runcalc host=rosterrun.herokuapp.com fwd="67.188.246.249" dyno=web.1 connect=2ms service=5604ms status=500 bytes=135
