2014-01-08T07:03:20.082680+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/workers/base.py", line 106, in init_process
2014-01-08T07:03:20.082680+00:00 app[web.1]:     self.callable = self.load()
2014-01-08T07:03:20.082680+00:00 app[web.1]:     return self.load_wsgiapp()
2014-01-08T07:03:20.082897+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/util.py", line 354, in import_app
2014-01-08T07:03:20.082897+00:00 app[web.1]:     return util.import_app(self.app_uri)
2014-01-08T07:03:20.082897+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 49, in load_wsgiapp
2014-01-08T07:03:20.082897+00:00 app[web.1]:     __import__(module)
2014-01-08T07:03:20.082897+00:00 app[web.1]:   File "/app/rosterrun.py", line 223
2014-01-08T07:03:20.082897+00:00 app[web.1]:     except:
2014-01-08T07:03:20.082897+00:00 app[web.1]:           ^
2014-01-08T07:03:20.082897+00:00 app[web.1]: IndentationError: unindent does not match any outer indentation level
2014-01-08T07:03:20.082897+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/arbiter.py", line 495, in spawn_worker
2014-01-08T07:03:20.083053+00:00 app[web.1]:     worker.init_process()
2014-01-08T07:03:20.083053+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/workers/base.py", line 106, in init_process
2014-01-08T07:03:20.083053+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/app/base.py", line 114, in wsgi
2014-01-08T07:03:20.083053+00:00 app[web.1]:     self.wsgi = self.app.wsgi()
2014-01-08T07:03:20.083053+00:00 app[web.1]:     self.callable = self.load()
2014-01-08T07:03:20.082897+00:00 app[web.1]: Traceback (most recent call last):
2014-01-08T07:03:20.083053+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 62, in load
2014-01-08T07:03:20.083053+00:00 app[web.1]:     return self.load_wsgiapp()
2014-01-08T07:03:20.083053+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 49, in load_wsgiapp
2014-01-08T07:03:20.083053+00:00 app[web.1]:     return util.import_app(self.app_uri)
2014-01-08T07:03:20.083053+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/util.py", line 354, in import_app
2014-01-08T07:03:20.083453+00:00 app[web.1]:     __import__(module)
2014-01-08T07:03:20.083453+00:00 app[web.1]: IndentationError: unindent does not match any outer indentation level
2014-01-08T07:03:20.083453+00:00 app[web.1]:   File "/app/rosterrun.py", line 223
2014-01-08T07:03:20.083453+00:00 app[web.1]:     except:
2014-01-08T07:03:20.083453+00:00 app[web.1]:           ^
2014-01-08T07:03:20.086481+00:00 app[web.1]: 2014-01-08 07:03:20 [7] [INFO] Worker exiting (pid: 7)
2014-01-08T07:03:20.330913+00:00 app[web.1]: 2014-01-08 07:03:20 [2] [INFO] Reason: Worker failed to boot.
2014-01-08T07:03:20.330704+00:00 app[web.1]: 2014-01-08 07:03:20 [2] [INFO] Shutting down: Master
2014-01-08T07:03:22.474565+00:00 heroku[web.1]: Process exited with status 3
2014-01-08T07:03:22.479957+00:00 heroku[web.1]: State changed from starting to crashed
2014-01-08T07:03:35.921299+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path=/ host=rosterrun.herokuapp.com fwd="107.16.122.17" dyno= connect= service= status=503 bytes=
2014-01-08T07:06:35+00:00 heroku[slug-compiler]: Slug compilation started
2014-01-08T07:07:38.730976+00:00 heroku[api]: Deploy 5ca613d by andygee@gmail.com
2014-01-08T07:07:38.767471+00:00 heroku[api]: Release v109 created by andygee@gmail.com
2014-01-08T07:07:38+00:00 heroku[slug-compiler]: Slug compilation finished
2014-01-08T07:07:39.597678+00:00 heroku[web.1]: State changed from crashed to starting
2014-01-08T07:07:50.433323+00:00 heroku[web.1]: Starting process with command `gunicorn rosterrun:app`
2014-01-08T07:07:51.563200+00:00 app[web.1]: 2014-01-08 07:07:51 [2] [INFO] Starting gunicorn 18.0
2014-01-08T07:07:51.563806+00:00 app[web.1]: 2014-01-08 07:07:51 [2] [INFO] Listening at: http://0.0.0.0:56981 (2)
2014-01-08T07:07:51.563939+00:00 app[web.1]: 2014-01-08 07:07:51 [2] [INFO] Using worker: sync
2014-01-08T07:07:51.571241+00:00 app[web.1]: 2014-01-08 07:07:51 [7] [INFO] Booting worker with pid: 7
2014-01-08T07:07:51.770867+00:00 heroku[web.1]: State changed from starting to up
2014-01-08T07:07:58.119526+00:00 app[web.1]: cannot find gdoc name
2014-01-08T07:07:58.119526+00:00 app[web.1]: show entries
2014-01-08T07:07:58.119526+00:00 app[web.1]: already have ids in session  t0r5xf97B-k70k6TxherGcw od6
2014-01-08T07:07:58.331325+00:00 app[web.1]: AVAILABLE PARTIES 0 
2014-01-08T07:07:58.331325+00:00 app[web.1]: get all combinations
2014-01-08T07:07:58.366292+00:00 heroku[router]: at=info method=GET path=/ host=rosterrun.herokuapp.com fwd="107.16.122.17" dyno=web.1 connect=0ms service=254ms status=200 bytes=1051
2014-01-08T07:08:01.913475+00:00 heroku[router]: at=info method=GET path=/logout host=rosterrun.herokuapp.com fwd="107.16.122.17" dyno=web.1 connect=1ms service=14ms status=302 bytes=209
2014-01-08T07:08:01.993938+00:00 heroku[router]: at=info method=GET path=/ host=rosterrun.herokuapp.com fwd="107.16.122.17" dyno=web.1 connect=0ms service=5ms status=302 bytes=219
2014-01-08T07:08:02.083047+00:00 heroku[router]: at=info method=GET path=/login host=rosterrun.herokuapp.com fwd="107.16.122.17" dyno=web.1 connect=0ms service=11ms status=200 bytes=563
2014-01-08T07:08:05.352032+00:00 app[web.1]: running with user andygee@gmail.com 
2014-01-08T07:08:05.367114+00:00 heroku[router]: at=info method=POST path=/login host=rosterrun.herokuapp.com fwd="107.16.122.17" dyno=web.1 connect=1ms service=16ms status=302 bytes=803
2014-01-08T07:08:06.380664+00:00 heroku[router]: at=info method=GET path=/auth_return?code=4/ClwMA7-2pzRzJLdyfyDv_R3ln854.0tBpVMcnIpYTmmS0T3UFEsMyl1_hhgI host=rosterrun.herokuapp.com fwd="107.16.122.17" dyno=web.1 connect=1ms service=584ms status=302 bytes=209
2014-01-08T07:08:06.463460+00:00 app[web.1]: show entries
2014-01-08T07:08:06.481352+00:00 app[web.1]: AVAILABLE PARTIES 0 
2014-01-08T07:08:06.481352+00:00 app[web.1]: get all combinations
2014-01-08T07:08:06.463460+00:00 app[web.1]: cannot find gdoc name
2014-01-08T07:08:06.463881+00:00 app[web.1]: already have ids in session  t0r5xf97B-k70k6TxherGcw od6
2014-01-08T07:08:06.492402+00:00 heroku[router]: at=info method=GET path=/ host=rosterrun.herokuapp.com fwd="107.16.122.17" dyno=web.1 connect=1ms service=32ms status=200 bytes=1100
2014-01-08T07:08:10.662658+00:00 app[web.1]: running with user andygee@gmail.com 
2014-01-08T07:08:11.222920+00:00 app[web.1]: trying to find the spreadsheet named Quest Status 
2014-01-08T07:08:11.223207+00:00 app[web.1]: ['Quest Status']
2014-01-08T07:08:11.223207+00:00 app[web.1]: t0r5xf97B-k70k6TxherGcw
2014-01-08T07:08:12.203824+00:00 app[web.1]: trying to find the spreadsheet named Quest Status 
2014-01-08T07:08:12.203824+00:00 app[web.1]: ['Quest Status']
2014-01-08T07:08:12.203824+00:00 app[web.1]: t0r5xf97B-k70k6TxherGcw
2014-01-08T07:08:15.103676+00:00 app[web.1]: Traceback (most recent call last):
2014-01-08T07:08:15.105262+00:00 heroku[router]: at=info method=POST path=/ host=rosterrun.herokuapp.com fwd="107.16.122.17" dyno=web.1 connect=1ms service=4457ms status=500 bytes=135
2014-01-08T07:08:15.103676+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/workers/sync.py", line 131, in handle_request
2014-01-08T07:08:15.103676+00:00 app[web.1]:     respiter = self.wsgi(environ, resp.start_response)
2014-01-08T07:08:15.103676+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/flask/app.py", line 1836, in __call__
2014-01-08T07:08:15.103676+00:00 app[web.1]:     return self.wsgi_app(environ, start_response)
2014-01-08T07:08:15.101933+00:00 app[web.1]: found 6435 combinations
2014-01-08T07:08:15.103676+00:00 app[web.1]: 2014-01-08 07:08:15 [7] [ERROR] Error handling request
2014-01-08T07:08:15.103676+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/flask/app.py", line 1820, in wsgi_app
2014-01-08T07:08:15.103676+00:00 app[web.1]:     reraise(exc_type, exc_value, tb)
2014-01-08T07:08:15.103910+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
2014-01-08T07:08:15.103910+00:00 app[web.1]:     response = self.full_dispatch_request()
2014-01-08T07:08:15.103910+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
2014-01-08T07:08:15.103910+00:00 app[web.1]:     rv = self.handle_user_exception(e)
2014-01-08T07:08:15.103910+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
2014-01-08T07:08:15.103910+00:00 app[web.1]:     reraise(exc_type, exc_value, tb)
2014-01-08T07:08:15.103676+00:00 app[web.1]:     response = self.make_response(self.handle_exception(e))
2014-01-08T07:08:15.103676+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/flask/app.py", line 1403, in handle_exception
2014-01-08T07:08:15.104082+00:00 app[web.1]:     run_calculation()
2014-01-08T07:08:15.103910+00:00 app[web.1]:     return self.view_functions[rule.endpoint](**req.view_args)
2014-01-08T07:08:15.104082+00:00 app[web.1]:   File "/app/rosterrun.py", line 134, in show_entries
2014-01-08T07:08:15.104082+00:00 app[web.1]:     parties = run_scheduler_OAuth(credentials, session['doc'])
2014-01-08T07:08:15.104082+00:00 app[web.1]:   File "/app/rosterrun.py", line 261, in run_calculation
2014-01-08T07:08:15.104082+00:00 app[web.1]:   File "/app/scheduler.py", line 122, in run_scheduler_OAuth
2014-01-08T07:08:15.103910+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
2014-01-08T07:08:15.103910+00:00 app[web.1]:     rv = self.dispatch_request()
2014-01-08T07:08:15.103910+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
2014-01-08T07:08:15.104082+00:00 app[web.1]:     maxmapping = [[0 for j in range(len(combinationMapping.keys()) + 1)] for i in range(len(combinationMapping.keys()))]
2014-01-08T07:08:15.104082+00:00 app[web.1]: NameError: global name 'combinationMapping' is not defined
2014-01-08T07:08:15.104082+00:00 app[web.1]:     parties += combineByRoleAssignment(avChar, instance, quests, viablePartyIndex)
2014-01-08T07:08:15.104082+00:00 app[web.1]:   File "/app/scheduler.py", line 341, in combineByRoleAssignment
Terminate batch job (Y/N)? 
